_BASE_: "Base-STCSeg.yaml"
MODEL:
  WEIGHTS: "weights/MS_R_50_3x.pth"
  RESNETS:
    DEPTH: 50
  STCSEG:
    BOUNDARY:
      DILATION: 2
      WARMUP_ITERS: 1
      USE_DEPTH: True
      USE_OPTICAL_FLOW: True
      COLOR_THRESH: 0.3
      DEPTH_COLOR_THRESH: 0.3
      FLOW_COLOR_THRESH: 0.4
      SIMILARITY_METHOD: "X"
  BACKBONE:
    FREEZE_AT: 3
DATASETS:
  TRAIN: ("kitti_mots_train",)
  TEST: ("kitti_mots_val",)
SOLVER:
  BASE_LR: 0.0001
  STEPS: (2500, 5000) 
  GAMMA: 0.2
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "models/STC-Seg_MS_R_50_kitti_mots"
